CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key TEXT NOT NULL UNIQUE,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS nested_settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_id INTEGER,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES settings (id) ON DELETE CASCADE
);
