/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPreferencesRouteImport } from './routes/settings_.preferences'
import { Route as SettingsHotkeysRouteImport } from './routes/settings_.hotkeys'
import { Route as SettingsPreferencesLanguageRouteImport } from './routes/settings_.preferences_.language'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings_/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHotkeysRoute = SettingsHotkeysRouteImport.update({
  id: '/settings_/hotkeys',
  path: '/settings/hotkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesLanguageRoute =
  SettingsPreferencesLanguageRouteImport.update({
    id: '/settings_/preferences_/language',
    path: '/settings/preferences/language',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/preferences/language': typeof SettingsPreferencesLanguageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings/hotkeys': typeof SettingsHotkeysRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/preferences/language': typeof SettingsPreferencesLanguageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/settings_/hotkeys': typeof SettingsHotkeysRoute
  '/settings_/preferences': typeof SettingsPreferencesRoute
  '/settings_/preferences_/language': typeof SettingsPreferencesLanguageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/hotkeys'
    | '/settings/preferences'
    | '/settings/preferences/language'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/hotkeys'
    | '/settings/preferences'
    | '/settings/preferences/language'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings_/hotkeys'
    | '/settings_/preferences'
    | '/settings_/preferences_/language'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SettingsHotkeysRoute: typeof SettingsHotkeysRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsPreferencesLanguageRoute: typeof SettingsPreferencesLanguageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/preferences': {
      id: '/settings_/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/hotkeys': {
      id: '/settings_/hotkeys'
      path: '/settings/hotkeys'
      fullPath: '/settings/hotkeys'
      preLoaderRoute: typeof SettingsHotkeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/preferences_/language': {
      id: '/settings_/preferences_/language'
      path: '/settings/preferences/language'
      fullPath: '/settings/preferences/language'
      preLoaderRoute: typeof SettingsPreferencesLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SettingsHotkeysRoute: SettingsHotkeysRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsPreferencesLanguageRoute: SettingsPreferencesLanguageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
